Hyunseo
programmers-lecture/java-baseball pull request #1
Opened 2022-09-21 12:43 UTC by hyena0608

야구 숫자 게임 

최대한 분리하면서 구현해봤습니다.

공, 플레이어, 힌트, 게임으로 나누어져 있고 최대한 자신의 일만 할 수 있게 구현하려고 했습니다.

구현 하면서 신경 쓰이는 부분이 있었는데

1. 메시지 입출력
    - 메시지를 자체는 enum으로 관리한다고 해도 결국 객체를 불러서 행동을 넘겨줘야 하는데 좀 더 깔끔한 방법이 없을지 고민하고 있습니다.
2. 메시지 관리
    - 메시지를 enum으로 관리한다고 했을 때 여러 개로 눠서 구분한다면 아예 message 폴더를 따로 분리하는게 좋을지 고민됩니다

2022-09-23 15:53 UTC, ksy90101 requested changes
안녕하세요 현서님 :)
숫자야구게임도 고생 많으셨습니다 💯 
코드의 오류가 있어, 리뷰를 멈추었습니다. 그래도 몇가지 남겨둔것이 있기 떄문에 참고해보시면 좋을거 같습니다.
전체적으로 수정이 끝나시면 코멘트로 핑을 주시면 좋을거 같습니다.

질문이 있다면 자유롭게 LMS 코드리뷰 게시판 또는 코멘트로 남겨주세요!

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/ball/Balls.java
> +        return balls;
일급 컬렉션을 고려해보시고 구현해주신거 같네요.
객체 상태는 외부에 노출이 될때, 상태를 변경하지 않도록 하는것이 중요합니다.
그렇기 떄문에 불변인 상태를 만드는 것이 좋은데요.
```suggestion
    return Collections.unmodifiableList(balls);
```
이런식으로 작성한다면 가능할거 같아요.

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/ball/Balls.java
> +    }
상태에 대한 validate는 객체의 중요한 책임중 하나 인거 같습니다.
이 경우에는 Ball을 3개만 가져야 하는 validate가 존재할듯 하네요.

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/util/FixedNumberGenerator.java
> +    }
```suggestion
    private boolean checkNumberSize(List<Integer> fixedNumbers) {
        return fixedNumbers.size() == GAME_SETTING_VERSION_01.getBallSize()
    }
```

이런식으로 작성하는 것이 훨씬 가독성도 높고 굳이 쓸데 없는 코드들이 들어가지 않아도 될거 같습니다.

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/util/FixedNumberGenerator.java
> +                .orElseThrow(() -> new NumberFormatException("올바르지 않은 포맷입니다.")); // TODO : Exception 관리
Exception 관리는 어떤걸 의미하는걸까요?

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/view/input/InputHandler.java
> +public class InputHandler {
static 메서드만 존재할 경우, 생성자를 생성하지 못하도록 하는것이 좋습니다.

https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

위 글을 한번 참고해보면 좋을거 같습니다 :)

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/view/input/InputHandler.java
> +    private final static InputView inputView = new InputView();
이런 경우에는 final static이 아니라 static final로 작성하는 편입니다.

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/view/input/InputValidation.java
> +        return false;
```suggestion
        return input.length() == 0
```

이런식이 좋을거 같아요.

2022-09-23 15:53 UTC, ksy90101 commented on src/main/java/game/baseball/game/GameHandler.java
> +        human.playGame();
리뷰를 남기던 중, 코드를 보니 이 부분에서 에러를 발생시킵니다.
동작하지 않은 애플리케이션은 아무리 깔끔해도 애플리케이션의 가장 큰 목적인 기능 동작이 되지 않기 떄문에, 가장 최악의 상태인데요.
이 부분을 수정해주시면 좋을듯 합니다.

동작하는 대로 다시 리뷰 진행할게요.

2022-09-23 16:14 UTC, ksy90101 commented
1. 메시지를 enum으로 관리한다고 했을 때 여러 개로 눠서 구분한다면 아예 message 폴더를 따로 분리하는게 좋을지 고민됩니다
- 네 message 폴더를 두는것이 좋을거 같습니다 👍

2022-09-24 09:02 UTC, SeokRae reviewed
안녕하세요.!

클래스 구성을 재미나게 하셔서 분석 하는데 재미있었습니다.
몇가지 피드백 남겼습니다. 확인 부탁드립니다. !

![CleanShot 2022-09-24 at 17 30 52](https://user-images.githubusercontent.com/17922700/192088647-4e6d2144-edec-45cd-b7c9-1578b63ec41d.png)

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/game/Game.java
> +public class Game {
의도를 보면 Game을 진행할 때 필요한 구성요소로 참여자들을 모아 놓은 것 처럼 보이는데,
실상 열어보면 의미가 없어 보이는 클래스 이긴 합니다.

참여하는 모든 대상을 묶어주는 기준을 클래스 레벨이 아닌 패키지 레벨로 사용하셔도 무관 해보입니다.

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/game/Game.java
> +    private int round;
사용하지 않는 필드군요!

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/game/GameHandler.java
> +//
사용하시지 않는 주석은 삭제하셔도 무방해보입니다.!

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/player/ComputerPlayer.java
> +    private final NumberGenerator numberGenerator;
```suggestion
    private final NumberGenerator numberGenerator;
    private Balls balls;
```

이건 관습적이긴한데 순서가 바뀌어야 겠군요.!

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/player/HumanPlayer.java
> +    private final NumberGenerator numberGenerator;
```suggestion
    private final NumberGenerator numberGenerator;
    private Balls balls;
```

ComputerPlayer의 내용과 같습니다.

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/util/setting/GameSetting.java
> +public enum GameSetting {
enum으로 구성하시는 내용을 보니 GameSetting도 Enum 으로 구성해도 좋지 않을까 하는데 어떠신가요?

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/util/setting/PlayerSetting.java
> +public class PlayerSetting {
숫자를 생성하는 기능을 담당하는 클래스를 묶는 것이 꼭 필요할까? 라는 생각이 듭니다.
그리고 그 두 기능을 관리하는 것도 아니고, PlayerSetting이라는 클래스명으로 묶여있는데 마찬가지로 패키지로 구분하는 정도로 해도 가능하지 않을까요?

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/view/input/InputValidation.java
> +public class InputValidation {
InputHandler 내에 체크하지 않고 별도의 클래스로 분리하신 이유가 궁금합니다.!

2022-09-24 09:02 UTC, SeokRae commented on src/main/java/game/baseball/view/input/InputHandler.java
> +public class InputHandler {
Handler는 어떤 역할을 하는 개념일까요? 어디 범위까지를 Handler라고 정의하셨을까요? 궁금합니다.!

2022-09-24 14:50 UTC, hyena0608 commented on src/main/java/game/baseball/ball/Balls.java
> +        return balls;
외부에 객체가 노출 될 때 변경이 되면 안되는 값이니 최대한 보장 해주는게 좋군요 
Unmodifiable Collection에 대해서 몰랐는데 이번에 학습할 수 있었고
다른 방법으로 방어적 복사를 이용해서 
`new ArrayList<>(balls)` 이런 식으로 반환할 수도 있다는 것도 알 수 있었습니다 !

2022-09-24 14:58 UTC, hyena0608 commented on src/main/java/game/baseball/ball/Balls.java
> +    }
자신의 상태를 검증하는 로직을 Balls에 추가할 수 있었습니다 !
실제로 애플리케이션을 실행한 후 공의 개수가 자유로운 것을 확인하였고
곧 바로 검증 로직을 작성할 수 있었습니다.

2022-09-24 15:03 UTC, hyena0608 commented on src/main/java/game/baseball/util/FixedNumberGenerator.java
> +                .orElseThrow(() -> new NumberFormatException("올바르지 않은 포맷입니다.")); // TODO : Exception 관리
Exception 메시지를 따로 보관하는 것을 의미하고 작성 했었습니다.
하지만 Exception 메시지만 관리하는 것보다 사용자 정의 예외를 작성하여 사용하는 것이
더 나을지 고민됩니다.

현재는 아래와 같은 방식으로 수정했습니다.

1. Expception 메시지 관리
 Enum에 정말 메시지만 관리하는 방법을 생각했습니다.
```java
.orElseThrow() -> new NumberFormatException(ExceptionMessage.INPUT_FORMAT_ERROR.getErrorMessage()));
```

2022-09-24 15:06 UTC, hyena0608 commented on src/main/java/game/baseball/view/input/InputHandler.java
> +public class InputHandler {
현재 InputHandler 클래스가 유틸성 클래스이고
유틸성 클래스 같은 경우에는 생성하지 못하도록 막는게 좋은데
그 이유는 협업할 때 혼란을 초래할 수도 있어서군요 !

2022-09-24 15:08 UTC, hyena0608 commented on src/main/java/game/baseball/game/GameHandler.java
> +        human.playGame();
PR을 한 이후에 수정을 하면서 오류가 발생한거 같습니다.
제가 수정할게 없다고 느껴질 때 요청해서 피드백을 받았어야 했는데
중간에 수정하면서 혼란을 남긴 점 정말 죄송합니다.

2022-09-24 15:14 UTC, hyena0608 commented on src/main/java/game/baseball/game/Game.java
> +    private int round;
피드백 해주고 계신줄 모르고 제가 계속 커밋하고 있었습니다 ㅠㅠ
이후에 round는 야구 게임 round회 연속 진행 시에 자동으로 게임이 종료가 되는 방식으로 구현했습니다.
아직 Game 클래스가 살아 있어서 알님이 말씀해주신데로 Game클래스를 없애고 패키지 레벨로 분리해보려고 합니다 !!

2022-09-24 15:21 UTC, hyena0608 commented on src/main/java/game/baseball/util/setting/PlayerSetting.java
> +public class PlayerSetting {
고민이 많이 됐던 부분이었습니다.
GameSetting에 설정할 수 있는 정보를 모두 한번에 모았다고 했을 때
버전 별로 관리하기 좋다고 생각해서 일부로 묶어두기로 했습니다.

만약 PlayerSetting을 삭제한다면
수정시에 HumanPlayer와 ComputerPlayer에 각각 NumberGenerator 를 넣어줘야 하는데
한 곳에서 관리하는게 더 편하지 않을까 생각했습니다.

2022-09-24 15:25 UTC, hyena0608 commented on src/main/java/game/baseball/view/input/InputValidation.java
> +public class InputValidation {
처음에 InputHandler에 모든 검증 부분을 작성하면 지저분해지니
아예 InputValidation을 만들어서 사용하는게 눈으로 보기에도 관리하기에도 편할 거 같아서
따로 빼놓았습니다.

하지만 실제로 검증하는 로직이 크게 있지는 않아서 합치는게 맞지만
만약 검증하는 로직이 많다면 Validation을 따로 빼서 만드는게 더 효과적이라고 생각이 드는데 
**알님은 어떻게 생각하시는지 궁금합니다 !**

2022-09-25 02:31 UTC, SeokRae commented on src/main/java/game/baseball/view/input/InputValidation.java
> +public class InputValidation {
유효성 검사에 대한 책임을 어떤 쪽에서 갖도록 정의 하였는가가 주안점이 되지 않을까 싶었습니다.
로직 구성상 사용자로부터 입력받은 값을 inputhandler에서 처리하는 것 같아보여 그 안에서 메서드 레벨로 만들거나 그 안에 inner 클래스로 구성해도 되지 않을까 생각했습니다!

현재 기능의 범위는 사용자가 "입력한 값에 대한 유효성 검사"니까 그 범위 안에서 코드를 구성하기만 하면 될 것 같습니다!

2022-09-25 03:58 UTC, hyena0608 commented on src/main/java/game/baseball/view/input/InputHandler.java
> +public class InputHandler {
읽어오고, 변환하고, 검증하는 3가지 기능을 InputHandler에서 하도록 했습니다.

때문에 Balls에서 형에 맞게 변환하는 것이 아닌
InputHandler에서 형 변환을 진행하였습니다.

Balls는 공에 대한 정보를 가질뿐이지 형을 변환하는 역할을 맞지 않다고 생각했기 때문입니다


Handler라는 단어를 붙이는 이유가 
어떠한 특정한 형식에 대한 메서드들을 갖고 있는 것이라 알고 있기 때문이고
입력 값에 관련된 메서드들을 가지고 있으므로 InputHandler라 이름 짓게 되었습니다. !

2022-11-13 13:27 UTC, merged