[4기][김동규] 숫자 야구
programmers-lecture/java-baseball pull request #17
Opened 2023-01-24 12:12 UTC by ehdrbrb

안녕하세요, 숫자 야구를 구현해 보았습니다.
피드백 주시면 열심히 개선해 보겠습니다.

과정 진행 중 궁금한 점이 생겨 질문 남깁니다.
단일 책임 원칙에 따라 클래스를 나눴을 때 어느 정도까지 나누어야 할지 잘 모르겠습니다.
예를 들면
숫자 야구에서 저는 GameResult라는 클래스를 만들어 게임 결과와 관련된 일은 GameResult가 하도록 하였지만
BaseballGame 클래스에서 gameResult()메소드를 만들어 게임 결과와 관련된 처리를 하는 방법도 있는 것 같습니다.
문자열 계산기에서는 Calculator 클래스에서 계산을 수행하게 하는 방법도 있지만, 사칙연산에 1:1로 대응되는 클래스를 만들어 해당 클래스를 통해 사칙연산을 수행하게 만드는 방법도 있는 것 같습니다.

감사합니다.

2023-01-25 11:03 UTC, ksy90101 commented on src/main/java/application/Application.java
> +            if(input == 2) again = false;
1,2에 대해서 enum으로 관리하면, 어떤 의미인지 잘 알수 있을듯 하네요!

2023-01-25 23:22 UTC, SeokRae reviewed
안녕하세요. 동규님 숫자야구 게임 프로젝트도 고생하셨습니다.

---

> 과정 진행 중 궁금한 점이 생겨 질문 남깁니다.
> 단일 책임 원칙에 따라 클래스를 나눴을 때 어느 정도까지 나누어야 할지 잘 모르겠습니다.

현재 프로젝트, 클래스에 단일책임원칙 이라고 하는 개념을 어떻게 적용해야 할 지 고민을 하시는 것 같은데요. 
제가 추천하고 싶은 방법은 클래스에 로직을 작성해 놓고, 코드를 말로 풀어서 연관된 문장들끼리 한번 묶어보시는 것을 추천드립니다.

연관된 문장끼리 그룹핑할 수 있다는 것은 코드의 연관성을 의미하기도 하고, 변경사항이 생길 때 영향을 미칠 수 있는 코드끼리도 묶인다는 의미로 볼 수 있습니다.

작성하신 코드에 대해서 변경된 요구사항이 생긴다면? 연관된 코드만을 묶어서 메서드로 또는 객체로 분리할 수 없을까 고민해보시면 좋을 것 같습니다.

2023-01-25 23:23 UTC, SeokRae commented on src/main/java/application/Application.java
> +            if(input == 2) again = false;
사용자의 입력과 그 유효성 검사를 처리하는 코드를 별도의 객체로 관리하는 것도 가능할 것 같습니다.

2023-01-26 00:24 UTC, ksy90101 commented on src/main/java/application/baseballGame/Computer.java
> +            int number = random.nextInt(9) + 1;
9의 값도 매직넘버입니다.

아울러 랜덤값을 이와 같이 생성하면 차후에 제어하기가 어려워질꺼에요.

https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/

위 글을 참고해서 인터페이스로 추출 후 랜덤값을 관리해볼까요?

2023-01-26 00:24 UTC, ksy90101 commented on src/main/java/application/baseballGame/GameResult.java
> +        }
숫자야구에서 배운 Enum을 통해 낫싱, 스트라이크, 볼을 관리할수 있을거라고 생각합니다.
한번 enum을 이용해 이것 또한 전략으로 만들어 볼까요?

2023-01-26 00:25 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니, 확인해주세요 :)

2023-01-26 06:23 UTC, SeokRae commented on src/main/java/application/baseballGame/BaseballGame.java
> +package application.baseballGame;
패키지 컨벤션에 대해서 한번 체크해보시는 것이 좋을 듯 합니다.

[패키지 명 convention](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

2023-01-26 06:39 UTC, SeokRae commented on src/main/java/application/baseballGame/BaseballGame.java
> +    static final int NUMBER_COUNT_RULE = 3;
```suggestion
    public static final int NUMBER_COUNT_RULE = 3;
```

요 상수는 Computer, User, GameResult에서 사용되는 것으로 보여집니다.

특정 객체에서만 사용되는 필드라면 관련 클래스에 정의되어 있는 것이 좋을 것 같고, 
현재 도메인과 관련된 클래스에서만 사용되는 상수라면 enum으로 정의한 뒤에 전역에서 사용할 수 있도록 제공하는 방법도 있을 것 같습니다.

2023-02-02 12:12 UTC, ksy90101 commented on src/main/java/application/baseballgame/Computer.java
> +            int number = numberGenerator.generate();
이렇게 하면, 이 메서드를 테스트 하기가 어려울듯 합니다.
더 밖으로 빼서 인자로 numberGenerator를 받아 단순히 실행하도록 하게 된다면 이 메서드에서 numbers의 제어가 가능할듯 해요.

2023-02-02 12:15 UTC, ksy90101 commented on src/main/java/application/baseballgame/GameResult.java
> +    }
view에 대한 코드가 여기 있는게 어색하네요.
출력하는 클래스는 따로 있고, 여기서는 단순히 result에 대한 부문만 내려주면 어떨까요?

2023-02-02 12:16 UTC, ksy90101 commented on src/main/java/application/numbergenerator/NumberGenerator.java
> +public interface NumberGenerator {
👍

2023-02-02 12:16 UTC, ksy90101 commented on src/main/java/application/input/Input.java
> +    private List<Integer> stringToIntegerList(String input) {
깔끔히 잘 구현해주셨네요 👍

2023-02-02 12:17 UTC, ksy90101 commented on src/main/java/application/input/Input.java
> +        return Arrays.stream(input.split("")).distinct().count() == Rule.NUMBER_COUNT.value();
Arrays.stream(input.split(""))
        .distinct()
        .count() 

이 부분에 대한 의미가 무엇인지 변수로 빼놓는다면 의미 전달이 더 잘될듯 해요.

2023-02-02 12:17 UTC, ksy90101 commented on src/main/java/application/input/Input.java
> +        }
valid는 validUserNumbers에서 에러를 발생시키튼게 더 좋아보입니다.

2023-02-15 03:30 UTC, ksy90101 approved these changes
숫자야구 게임 하시느라 고생 많으셨습니다~
테스트 코드가 조금 부족한데 그건 2단계에서 잘 진행해주실거라 믿습니다!
2단계때 봐요~

2023-02-15 03:30 UTC, ksy90101 commented on src/main/java/application/baseballgame/gameresult/GameResult.java
> +    private static final int MAX = Rule.NUMBER_COUNT.value();
이미 NUMBER_COUNT가 상수의 역할을 하고 있기 떄문에 이와 같이 사용할 필요가 없어보입니다 :)

2023-02-15 03:30 UTC, ksy90101 commented on src/main/java/application/baseballgame/gameresult/GameResult.java
> +        for (int i = 0; i < Rule.NUMBER_COUNT.value(); i++) {
i라는 단어보단 더 의미있는 변수명을 사용해보면 어떨까요?

2023-02-15 03:30 UTC, ksy90101 commented on src/main/java/application/baseballgame/gameresult/ThrowingResult.java
> +        return NOTHING;
IF문에 있는 내용을 함수형 인터페이스로 빼서 관리한다면 훨씬 보기 깔끔할거 같아요!

2023-02-15 03:30 UTC, ksy90101 commented on src/test/java/application/baseballgame/gameresult/GameResultTest.java
> +    static void init() {
👍 BeforeAll 굿입니다!

2023-02-15 03:30 UTC, merged