[1기][고범준] 숫자 야구 게임
programmers-lecture/java-baseball pull request #2
Opened 2022-09-21 13:03 UTC by K-jun98

안녕하세요! 알 & 마르코님 이번 리뷰도 잘 부탁드립니다! 
이번 야구게임을 구현하면서 고민했던 점과 궁금했던 점은
1. InputView 의 책임은 어디까지인가? 숫자를 List로 변환해서 줘도될까요?
2. 문자열 계산기에서 리뷰해주셨던 전략패턴을 적용해 보았는데 이렇게 사용해도 되는걸까요?
3.  Referee도 도메인이 맞는지 서비스로 봐야하는지? 도메인과 서비스의 구분을 잘 못하겠습니다 ㅠ
그리고 enum을 많이 사용해 본적이 없어서 Score를 enum으로 사용해 봤는데 이 부분에서 피드백 많이 주시면 감사하겠습니다,,
감사합니다! ㅎㅎ

2022-09-23 16:10 UTC, ksy90101 requested changes
안녕하세요 범준님 :)
숫자야구게임도 잘 구현해주셨네요 💯 
고생많으셨습니다!
간단한 피드백을 드렸으니, 참고해보시면 좋을거 같습니다.

질문이 있다면 언제든 LMS 질문답변 게시판 또는 코멘트로 남겨주시면 감사하겠습니다!

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/Application.java
> +    private static boolean playGame = true;
쓰이지 않는 변수는 삭제해주세요.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/Application.java
> +    private static Game game;
굳이 static으로 해야할까요? 또한 전역변수로요.
main에서 실행해두는것과 동일하긴 한데, 그냥 main에 넣는게 더 깔끔해 보이긴 합니다.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/Application.java
> +}
이전 공통 피드백처럼, 개행도 의미를 가지고 있습니다.
의미없는 개행은 삭제해주세요.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Balls.java
> +    }
Return of boolean Exception이 훨씬 보기에 깔끔합니다.

```suggestion
    public boolean getStrike(Balls userBalls, int index) {
        return balls.get(index).equals(userBalls.balls.get(index))
    }
```

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Balls.java
> +    }
return of boolean Exception이 훨씬 보기에 깔끔합니다.

```suggestion
    public boolean getBall(Balls userBalls, int i) {
        return balls.contains(userBalls.balls.get(i)) && !getStrike(userBalls, i))
    }
```

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Balls.java
> +    public boolean getStrike(Balls userBalls, int index) {
getter는 상태를 리턴할때 사용하며, boolean인 경우엔 is나 has를 사용하는 편입니다.

아울러 상태에 대해서 한번 enum으로 관리해보면 어떨까요?

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/contoller/Game.java
> +    private static boolean isReplay = true;
이런 경우에 동시에 게임이 진행되고 있을때, 누군가 종료하면 모두다 종료되겠어요 😢

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/contoller/Game.java
> +    private Referee referee;
전역변수를 가지고 있어야 할까요?

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/view/InputView.java
> +            throw new RuntimeException(INPUT_ERROR_MSG);
더 의미있는 예외로 작성해주셔야 나중에 예외 핸들링 시, 편합니다.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/view/InputView.java
> +        if (Pattern.matches("^\\d{3}", numbers)) {
Patten 객체는 비싼 객체인데요.
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/6_%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C_%EA%B0%9D%EC%B2%B4_%EC%83%9D%EC%84%B1%EC%9D%84_%ED%94%BC%ED%95%98%EB%9D%BC_%EC%8B%A0%EC%84%A0%EC%98%81.md
한번 위글을 참고해보시면 좋을거 같습니다.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/util/RandomNumberImpl.java
> +        return Stream.generate(() -> (int) (Math.random() * Ball.MAX_BALL_NUMBER) + Ball.MIN_BALL_NUMBER)
Random r = new Random();
int rand = r.nextInt(50);  // returns pseudo-random value between 0 and 50
이런식으로 작성하는게 더 깔끔할수도 있습니다. 형변환도 안일어 나구요 :)

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/util/RandomNumberImpl.java
> +            .collect(Collectors.toList());
혹시라도, 외부에서 해당 값을 변경해도 괜찮을까요?
이런 경우엔 불변으로 처리하긴 합니다.

            .collect(Collectors.toUnmodifiableList());

이런식으로 작성할 수 있죠.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/util/RandomNumber.java
> +public interface RandomNumber {
👍

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Score.java
> +    }
이 부분도 Return of Boolearn Expression 방식으로 사용해부세요.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Score.java
> +        return STRIKE.point + STRIKE_MSG + BALL.point + BALL_MSG;
함수형 인터페이스를 이용해, 전략적으로 관리해보면 어떨까요?

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/view/InputView.java
> +public class InputView {
3개의 이상값이 나오면 애플리케이션이 터집니다.
validate를 해보면 좋을거 같아요.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Balls.java
> +        List<Ball> balls = numbers.stream().map(i -> (new Ball(i)))
i보단, 더 의미있는 변수명을 작성하는걸 추천드립니다.

2022-09-23 16:10 UTC, ksy90101 commented on src/main/java/baseball/domain/Balls.java
> +        List<Ball> balls = numbers.stream().map(i -> (new Ball(i)))
아울러 해당 코드는 테스트 코드를 위한거 같은데, 맞을까요?
테스트 코드를 위한 프로덕션 코드는 굉장히 좋지 않은 안티패턴입니다.
숫자를 제어하고 싶다면 테스트 코드 내에서 인터페이스를 기반으로 한 Mock을 만들어서 처리해보세요 👍

2022-09-23 16:12 UTC, ksy90101 commented
1. InputView 의 책임은 어디까지인가? 숫자를 List로 변환해서 줘도될까요?
View의 역할은 단순히 입력을 받고 입력을 받은 값에 대한 validate의 역할이라고 생각합니다. 입력을 받은 실제 실행 객체에서 변환하는게 더 좋다고 생각은 합니다. 이건 저의 단순한 생각이여서, 참고만 하시면 좋을거 같습니다.
3. 문자열 계산기에서 리뷰해주셨던 전략패턴을 적용해 보았는데 이렇게 사용해도 되는걸까요?
굳굳 👍 
4. Referee도 도메인이 맞는지 서비스로 봐야하는지? 도메인과 서비스의 구분을 잘 못하겠습니다 ㅠ
Referee가 하는 일이 무엇인지 한번 설명해주실수 있나요? 어떤걸 의미하는지요!
5. 그리고 enum을 많이 사용해 본적이 없어서 Score를 enum으로 사용해 봤는데 이 부분에서 피드백 많이 주시면 감사하겠습니다,,
👍 
6. 추가로 볼과 스트라이크 구하는 로직을 스트림으로 해보고 싶었는데.. 실패했습니다 ㅠㅠ 리뷰어분들의 생각은 어떠신지 궁금합니다.
- 스트림이 사용이 어렵다면, 충분히 반복문으로 하셔도 됩니다. 스트림에 너무 얽매이진 마세요!

2022-09-23 16:16 UTC, K-jun98 commented on src/main/java/baseball/Application.java
> +    private static boolean playGame = true;
수정하겠습니다!

2022-09-23 16:18 UTC, K-jun98 commented on src/main/java/baseball/Application.java
> +    private static Game game;
수정하겠습니다! 이 부분은 수정하면서 궁금한 점이 있어서 여쭤보겠습니다!

2022-09-23 16:18 UTC, K-jun98 commented on src/main/java/baseball/Application.java
> +}
수정하겠습니다

2022-09-23 16:21 UTC, K-jun98 commented on src/main/java/baseball/domain/Score.java
> +    }
수정해보겠습니다!

2022-09-23 16:23 UTC, K-jun98 commented on src/main/java/baseball/domain/Balls.java
> +        List<Ball> balls = numbers.stream().map(i -> (new Ball(i)))
테스트 코드를 생각하고 구현하진 않았는데 고민해보겠습니다..ㅎ

2022-09-23 16:28 UTC, K-jun98 commented on src/main/java/baseball/view/InputView.java
> +        if (Pattern.matches("^\\d{3}", numbers)) {
감사합니다 참고하겠습니다!

2022-09-24 09:25 UTC, SeokRae reviewed
안녕하세요.! 범준님

1주차 늦은 피드백이지만 몇 가지 피드백 남겨봤습니다.

확인 부탁드리겠습니다.!
![CleanShot 2022-09-24 at 18 11 29](https://user-images.githubusercontent.com/17922700/192090125-3b503ba0-467d-49d9-9e6e-99868a48aae4.png)

2022-09-24 09:25 UTC, SeokRae commented on src/main/java/baseball/Application.java
> +        while (game.getIsReplay()) {
game 객체는 초기화 되지 않았는데 getIsReplay라는 정적 메서드를 호출하는 군요?
그리고 userIsReplay에서 isReplay라는 필드를 다시 갱신하는데 이런 방식은 고민이 필요할 것 같습니다.

변경이 발생할 수 있는 필드 값이 static으로 제공되어야 하는가? 그러한 경우 어떤 문제가 발생할 수 있을까?
고민이 필요할 것 같습니다.

2022-09-24 14:09 UTC, K-jun98 commented on src/main/java/baseball/domain/Balls.java
> +    public boolean getStrike(Balls userBalls, int index) {
enum도 고려해보겠습니다!

2022-09-24 14:11 UTC, K-jun98 commented on src/main/java/baseball/view/InputView.java
> +            throw new RuntimeException(INPUT_ERROR_MSG);
넵! 조금더 자세히 적겠습니다!

2022-09-24 14:19 UTC, K-jun98 commented on src/main/java/baseball/util/RandomNumberImpl.java
> +            .collect(Collectors.toList());
감사합니다! 수정하겠습니다!

2022-09-25 06:55 UTC, K-jun98 commented on src/main/java/baseball/view/InputView.java
> +public class InputView {
수정해봤습니다!

2022-09-26 07:51 UTC, K-jun98 commented on src/main/java/baseball/Application.java
> +        while (game.getIsReplay()) {
수정했습니다!

2022-11-13 13:27 UTC, merged