[1기][최준아] 숫자 야구 게임
programmers-lecture/java-baseball pull request #3
Opened 2022-09-21 16:06 UTC by joona95

늦게나마 숫자 야구 게임 과제부터 제출합니다..! 🥲
아래는 숫자 야구 게임 과제 진행하면서 생각했던 부분, 궁금했던 부분들입니다.
- 이번엔 상속을 이용해보려고 했습니다. User -> Computer, Player
- 상속 사용하면서 궁금했던 점이 있습니다. 처음부터 객체 구조를 잘짜서 추상화 객체 만들고 상속받으면 좋겠지만, 처음에는 독립적으로 진행하다가 겹치는 부분이 많아져서 거꾸로 추상화를 하는 경우도 있나요?
- 아직 이전 과제를 수정은 못했지만 피드백 받았던 static 메소드만 사용하는 경우엔 생성자를 Private 가 되도록 했습니다.
- Baseball과 Computer, Player 에서 getter를 사용하게 됐는데, getter/setter 사용을 지양하라고 했는데 이 경우에 어떤 식으로 해야 지양할 수 있을지 궁금합니다.
- 원래 Baseball 객체에서 맞추기 전까지 반복하는 부분을 구현하려고 했는데, 입출력 때문에 views를 불러와야 해서 결국 Baseball에서는 입력받은 값과 비교하는 한 번에 대해서만 처리하도록 했습니다.
- 이번에는 저번에 잘 사용하지 못했던 stream을 Baseball에서 사용하여 좀 더 간결하게 표현하고자 했습니다.
- Game에서 전체 반복하는 부분과 Baseball 맞추기 전까지 반복하는 부분을 분리하고 싶었는데 어떻게 해야 잘 나누어질지 잘 모르겠습니다. 
- OutputView에서 케이스 별로 결과를 if로 처리하고 있는데 더 나은 표현 방법이 있을지 궁금합니다.

2022-09-24 07:32 UTC, ksy90101 requested changes
안녕하세요 :) 준아님

숫자야구게임도 고생 많으셨습니다 💯  
간단한 피드백을 남겼으니, 한번 확인해보시면 좋을거 같습니다.

질문은 언제든 환영입니다!

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Baseball.java
> +    private Integer ballCount = 0;
지금과 같은 케이스에선, boxedType보단, Primitive type을 쓰는것이 훨씬 효과적일거 같습니다.

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Computer.java
> +        return ball;
한번 ball이 생성되었다면, 불변을 유지해 데이터 문제가 없도록 하면 어떨까요?
collection.unmodifiablelist()를 사용하면 가능합니다 :)

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Baseball.java
> +        long strikeCount = IntStream.range(0, playerBall.size())
this.strikeCount = Math.toIntExact(IntStream.range(0, playerBall.size())
                .filter(idx -> playerBall.get(idx).equals(computerBall.get(idx)))
                .count());

이런식으로 사용하면 쉽게 형변환을 신경쓰면서 가능할거 같네요 :)

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Baseball.java
> +        this.ballCount = Long.valueOf(totalCount).intValue() - strikeCount;
```suggestion
        int totalCount = Math.toIntExact(playerBall.stream()
                .filter(computerBall::contains)
                .count());
        this.ballCount = totalCount - strikeCount;
    }
```

이런식으로 하면 더 깔끔하겠네요 :)

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/controller/Game.java
> +import java.util.List;
사용하지 않은 import는 삭제해주세요.

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/utils/RandomUtil.java
> +        Random random = new Random();
Random은 재사용하는것이 훨씬 성능상 좋습니다.
상수로 선언해서 재사용해보면 어떨까요?

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Baseball.java
> +    private Integer strikeCount = 0;
상수와 필드는 개행을 두고 분리해두면 훨씬 가독성이 높습니다.

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Baseball.java
> +    private Integer strikeCount = 0;
굳이 boxedType을 쓰신 이유가 있나요?

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Computer.java
> +    private List<Integer> ball = new ArrayList<>();
ball은 생성자에서 초기화시켜주는것이 더 좋습니다.

아울러 Collection은 복수로 이름을 짓습니다.

실제 해당 부분에선 볼이 여러개 있을거 같아요!

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Computer.java
> +            int randomNumber = RandomUtil.createRandomNumber();
이 행위가 외부에 노출해야 할 이유가 있을까요?
private이여도 무관할듯 한데요!

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Computer.java
> +        while(ball.size() < Baseball.BALL_SIZE) {
이 부분은 충분히 stream으로 작성이 가능할듯 한데, stream으로 한번 연습겸 변경해보면 어떨까요?

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Computer.java
> +    private List<Integer> ball = new ArrayList<>();
Ball도 한번 Wrap값으로 원시값 포장해보세요!

2022-09-24 07:32 UTC, ksy90101 commented on src/main/java/baseball/models/Player.java
> +    private List<Integer> ball = new ArrayList<>();
위의 값과 아래값은 중복인거 같은데요?
굳이 상태를 여러개 가질 필요가 잇나요? ball만 가져도 충불할거 같아요.

2022-09-24 07:35 UTC, ksy90101 commented
1. 이번엔 상속을 이용해보려고 했습니다. User -> Computer, Player 상속 사용하면서 궁금했던 점이 있습니다. 처음부터 객체 구조를 잘짜서 추상화 객체 만들고 상속받으면 좋겠지만, 처음에는 독립적으로 진행하다가 겹치는 부분이 많아져서 거꾸로 추상화를 하는 경우도 있나요?
네 충분히 가능한 일입니다. 아울러, `상속보단 컴포지션` 이라는 개념이 있는데요. 상속을 고려하기 전엔 컴포지션을 고려해봐도 좋을거 같습니다. 설계는 맨처음 고려햇을때 완벽할수 없습니다. 코드를 구현하면서 충분히 계속해서 변경해 나갈수 있습니다. 빠르게 구현해보고 빠르게 피드백을 받아 리팩토링을 하는 이러한 사이클이 개발 시, 많은 도움을 저는 받고 있습니다.
2. Baseball과 Computer, Player 에서 getter를 사용하게 됐는데, getter/setter 사용을 지양하라고 했는데 이 경우에 어떤 식으로 해야 지양할 수 있을지 궁금합니다.
- setter를 지양하는 이유는 자신의 상태를 외부에서 변경하기 때문이에요. 쉽게 현실세계에서 준아님의 키가 170cm인데, 다른 사람이 165cm으로 지정해리면 값이 이상해지는 경우가 생기겠죠? 이런 경우를 방지하기 위함이에요. 또한 getter를 지양하는 케이스는 조금 어려울수 있는데요. 충분히 해당 객체가 해당 값을 가공할수 있음에도, 외부에서 가공해서 쓰이는걸 막기 위함이에요.
3. Game에서 전체 반복하는 부분과 Baseball 맞추기 전까지 반복하는 부분을 분리하고 싶었는데 어떻게 해야 잘 나누어질지 잘 모르겠습니다.
지금도 충분히 잘 하고 있습니다 💯 
4. OutputView에서 케이스 별로 결과를 if로 처리하고 있는데 더 나은 표현 방법이 있을지 궁금합니다.
이부분은 제가 이야기 드렸던 상태를 enum으로 관리하게 되면 if문을 제거할수 있지 않을까요?

2022-09-27 10:24 UTC, joona95 commented on src/main/java/baseball/controller/Game.java
> +import java.util.List;
https://github.com/programmers-lecture/java-baseball/pull/3/commits/adb785b4a595fac8d0851df58deaec07399740ad
해당 부분 삭제하였습니다.

2022-09-27 10:25 UTC, joona95 commented on src/main/java/baseball/models/Baseball.java
> +    private Integer ballCount = 0;
https://github.com/programmers-lecture/java-baseball/pull/3/commits/6e7cd4f2beceaa6ced0e86bc6f50f8876c46d9fe
네 그런 것 같습니다. null 체크가 필요한 것도 아니고 딱히 이유없이 사용했네요. 수정했습니다.

2022-09-27 10:26 UTC, joona95 commented on src/main/java/baseball/models/Baseball.java
> +    private Integer strikeCount = 0;
https://github.com/programmers-lecture/java-baseball/pull/3/commits/6e7cd4f2beceaa6ced0e86bc6f50f8876c46d9fe
해당 부분 수정했습니다. 딱히 이유가 있어서 사용한 게 아니어서 Primitive Type으로 변경하였습니다.

2022-09-27 10:26 UTC, joona95 commented on src/main/java/baseball/models/Baseball.java
> +    private Integer strikeCount = 0;
https://github.com/programmers-lecture/java-baseball/pull/3/commits/f144972a339908c5302c02fa45cfc693ce349ca8
아하 넵 수정했습니다.

2022-09-27 10:27 UTC, joona95 commented on src/main/java/baseball/utils/RandomUtil.java
> +        Random random = new Random();
https://github.com/programmers-lecture/java-baseball/pull/3/commits/927080b836bf4d8834d279d67df3da354488631e
넵 해당 부분 상수 선언했습니다.

2022-09-27 10:28 UTC, joona95 commented on src/main/java/baseball/models/Computer.java
> +        return ball;
https://github.com/programmers-lecture/java-baseball/pull/3/commits/9b0deb63966b08a52d8e37a4a11664b3b8cf3df7
오 넵 collection.unmodifiablelist() 이용하여 해당 부분 수정하였습니다.

2022-09-27 10:29 UTC, joona95 commented on src/main/java/baseball/models/Baseball.java
> +        long strikeCount = IntStream.range(0, playerBall.size())
https://github.com/programmers-lecture/java-baseball/pull/3/commits/ca004fd1e6176dcfedb88e8483dc19ce70634fa0
형변환을 함께 할 수 있어서 좋네요. 참고해서 수정했습니다.

2022-09-27 10:30 UTC, joona95 commented on src/main/java/baseball/models/Baseball.java
> +        this.ballCount = Long.valueOf(totalCount).intValue() - strikeCount;
https://github.com/programmers-lecture/java-baseball/pull/3/commits/ca004fd1e6176dcfedb88e8483dc19ce70634fa0
참고해서 수정했습니다!

2022-09-27 10:31 UTC, joona95 commented on src/main/java/baseball/models/Player.java
> +    private List<Integer> ball = new ArrayList<>();
https://github.com/programmers-lecture/java-baseball/pull/3/commits/4f2a26a093b06d633611ff7aa0578c4daeb3b7f6
넵 확실히 그런 것 같습니다. 하나의 값만 가지도록 수정했습니다.

2022-09-27 10:31 UTC, joona95 commented on src/main/java/baseball/models/Computer.java
> +    private List<Integer> ball = new ArrayList<>();
https://github.com/programmers-lecture/java-baseball/pull/3/commits/c44f13eba64cc08f55237fb1815e3fde87cf4d58
이렇게 한 번 분리를 해보았습니다..!

2022-09-27 10:32 UTC, joona95 commented on src/main/java/baseball/models/Computer.java
> +        while(ball.size() < Baseball.BALL_SIZE) {
https://github.com/programmers-lecture/java-baseball/pull/3/commits/1c1ceef5ebe97a708aef902a91fe019970710012
이 부분 stream으로 이렇게 한 번 처리해봤습니다.

2022-09-27 10:33 UTC, joona95 commented on src/main/java/baseball/models/Computer.java
> +            int randomNumber = RandomUtil.createRandomNumber();
https://github.com/programmers-lecture/java-baseball/pull/3/commits/27319823f50bfe854e2b9ec0638d0b3145e9b156
interface에서 getter 말고 또 공통된 메서드가 뭐가 있을까 생각하면서 만들었어서 저렇게 진행했었습니다.
그런데 외부 노출할 필요가 없는 듯 해서 말씀하신대로 private로 변경하였습니다.

2022-09-27 10:34 UTC, joona95 commented on src/main/java/baseball/models/Computer.java
> +    private List<Integer> ball = new ArrayList<>();
https://github.com/programmers-lecture/java-baseball/pull/3/commits/c44f13eba64cc08f55237fb1815e3fde87cf4d58
이부분 진행하면서 생성자에서 초기화를 하도록 했습니다.
https://github.com/programmers-lecture/java-baseball/pull/3/commits/f46d5855c5d64f2504bd5e3333a08858243431f6
collection 네이밍은 복수로 변경하였습니다!

2022-09-27 10:42 UTC, joona95 commented
리뷰 받고 리팩토링하면서 추가 고민 사항입니다.
1. STRIKE, BALL, NOTHING 을 Enum 통해서 처리하도록 추가하였는데, 더 잘 활용할 수는 없을까 고민되네요. (https://github.com/programmers-lecture/java-baseball/pull/3/commits/eb7e9cf0f3ef25011ee777c6cfbd0c00ef100220)
2. 공통피드백대로 List 말고 Set을 활용하려 하니 순서 문제가 생겨서 기존으로 일단 유지했는데요. Set을 할용하면서 순서 유지하려면 LinkedHashSet 을 이용하면 되는게 맞을까요?

2022-11-13 13:27 UTC, merged