[3기][조소영] 숫자 야구게임 과제
programmers-lecture/java-baseball pull request #7
Opened 2022-12-07 14:10 UTC by s2s22

* 추후 테스트 더 필요

2022-12-08 02:56 UTC, Jo-GyuHyeon requested changes
안녕하세요 소영님 😄 
숫자 야구게임하면서 도움이 될만한 피드백을 남겼으니 한번 확인해보시면 좋을것 같습니다. 

미션 가이드에 있는 것 처럼 개발을 시작하기 이전에 ReadMe 를 먼저 작성하는 것이 좋은 코드를 만들 수 있다고 생각합니다.

> 미션가이드
ReadMe에 각 객체에 대한 간단한 다이어그램(설명)을 작성한다.
ReadMe에 각 요구사항에 대한 체크 리스트를 작성한다.
커밋은 최소한의 단위로 진행한다.
객체지향 생활 체조를 지켜서 개발한다.

계산기의 코멘트와 동일하게 체크리스트, 다이어그램 등을 함께 적용해보시면 더 좋을것 같습니다.

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +        List list2 = new LinkedList();
띄어쓰기 혹은 들여 쓰기는 별개 아닐 수 있지만, 가독성에도 영향을 주는 중요한 요소입니다.
마치  `아버지 가방에 들어가신다. `  혹은 `아버지가 방에 들어가신다.` 와 같이 생각해주시면 좋을것 같습니다.

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +        List<String> list = ints.distinct().limit(3).boxed().map(Object::toString).collect(Collectors.toList());
list 라는 변수명 보다 조금더 의미 있는 네이밍을 부여 하면 어떨까요???

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +            list2 = Arrays.stream(str.split("")).collect(Collectors.toList());
`사용자가 잘못된 값을 입력할 경우 IllegalArgumentException을 발생시킨 후 애플리케이션은 종료되어야 한다.`
라는 요구사항을 아직 고려 하지 않은 것 같습니다.
사용자는 실수로 숫자가 아닌 문자를 입력 할 수 있기에 안전하게 유효성검사가 필요합니다.

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +                if(next.equals("2")) break;
위와 마찬가지로 1,2 가 아닌 다른 입력을 할때에 예외가 발생해야 합니다.

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +    }
불필요한 띄워쓰기는 줄여주세요 😄

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +            if(strike ==0 && ball ==0 ) System.out.println("낫싱");
`==0` 와 `ball ==0` 는 `== 0` , `ball == 0` 처럼 띄어쓰기를 잘 해주시면 가독성을 해치지 않습니다.

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +            list2 = Arrays.stream(str.split("")).collect(Collectors.toList());
또한 입력을 담당하는 클래스를 별도로 만들어 보면 어떨까요?

2022-12-08 02:56 UTC, Jo-GyuHyeon commented on src/main/java/BaseballMain.java
> +            ball = list2.size() - strike;
점수 계산들 담당하는 클래스를 별도로 만들어 보면 어떨까요?

2022-12-12 12:19 UTC, s2s22 commented
readme.md 체크리스트 확인부탁드립니다. 다이어그램은 완성해서 반영하겠습니다.
또한 입력과 계산 기능을 메서드가 아닌 클래스로 따로 구현을 말씀해주셨는데...만약 계산 클래스를 만든다면 계산 인스턴스를 생성하고 적용하면되는건지...클래스를 어떻게 만들지 힌트부탁드립니다...
그리고 객체지향적으로 만들고 싶은데 코멘트 해주신 입력과 계산기능을 클래스로 만들면 좀더 객체지향적으로 코드가 될것인지도 궁금합니다

2022-12-13 09:36 UTC, Jo-GyuHyeon commented
안녕하세요 소영님 😄
ReadMe 를 잘 작성해주셨군요. 👍 
아무래도 클래스를 나뉘기 어려울수 있다고 생각합니다. 그렇기에 미리 다이어그램을 작성하는 것이 도움이 될것이라 생각합니다.

객체지향적이라고 말씀드리면 객체들간의 메시지(메서드,리턴값) 을 이용하여 협력하는 관계를 이루는 것이라고도 말씀드릴수 있을 것 같습니다.
현재는 Main 이되는 메서드에서 모든 행위들이 일어나고 있으니 부분적으로 객체로 행위와 책임을 분리 할 수 있을 것이라 생각이 됩니다.
예시를 든다면, 입출력 부분, 점수를 계산하는 부분 들도 있습니다. 

아마 해당 부분은 이미 소영님께서 주석으로도 남기셔서 의미적으로 구분이 되어 있을겁니다. 해당부분은 객체로 위임을 하신다고 생각하시면 어떨까요? 그렇다면 객체에게 행동을 시키고 행동에 대한 값을 바탕으로 또다시 객체(들)에게 행동을 시킬수 있다고 생각이 됩니다.

2022-12-30 04:10 UTC, merged